terminal:
  # This can be any image that has the necessary runtime environment for your project.
  image: fedora:36
  before_script:
    - dnf update
  script: sleep 60
  variables:
    RAILS_ENV: "test"
    NODE_ENV: "test"
